inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'spec/rails_helper.rb'

Layout/LineLength:
  Max: 105

Metrics/BlockLength:
  Max: 65

Lint/NonDeterministicRequireOrder:
  Exclude:
    - 'spec/rails_helper.rb'

Style/EmptyMethod:
  Exclude:
    - 'app/controllers/**/*'

Style/StringLiterals:
  Exclude:
    - 'spec/**/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false


Style/FrozenStringLiteralComment:
  Enabled: false

Style/AsciiComments:
  Enabled: false